/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DirectorsRouteImport } from './routes/directors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmsTmdbIdRouteImport } from './routes/films/$tmdbId'
import { Route as PersonJobTmdbIdRouteImport } from './routes/person/$job/$tmdbId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorsRoute = DirectorsRouteImport.update({
  id: '/directors',
  path: '/directors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsTmdbIdRoute = FilmsTmdbIdRouteImport.update({
  id: '/$tmdbId',
  path: '/$tmdbId',
  getParentRoute: () => FilmsRoute,
} as any)
const PersonJobTmdbIdRoute = PersonJobTmdbIdRouteImport.update({
  id: '/person/$job/$tmdbId',
  path: '/person/$job/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/directors': typeof DirectorsRoute
  '/docs': typeof DocsRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/person/$job/$tmdbId': typeof PersonJobTmdbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/directors': typeof DirectorsRoute
  '/docs': typeof DocsRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/person/$job/$tmdbId': typeof PersonJobTmdbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/directors': typeof DirectorsRoute
  '/docs': typeof DocsRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/person/$job/$tmdbId': typeof PersonJobTmdbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/directors'
    | '/docs'
    | '/films'
    | '/login'
    | '/map'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/films/$tmdbId'
    | '/person/$job/$tmdbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/directors'
    | '/docs'
    | '/films'
    | '/login'
    | '/map'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/films/$tmdbId'
    | '/person/$job/$tmdbId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/directors'
    | '/docs'
    | '/films'
    | '/login'
    | '/map'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/films/$tmdbId'
    | '/person/$job/$tmdbId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DirectorsRoute: typeof DirectorsRoute
  DocsRoute: typeof DocsRoute
  FilmsRoute: typeof FilmsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  PersonJobTmdbIdRoute: typeof PersonJobTmdbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directors': {
      id: '/directors'
      path: '/directors'
      fullPath: '/directors'
      preLoaderRoute: typeof DirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$tmdbId': {
      id: '/films/$tmdbId'
      path: '/$tmdbId'
      fullPath: '/films/$tmdbId'
      preLoaderRoute: typeof FilmsTmdbIdRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/person/$job/$tmdbId': {
      id: '/person/$job/$tmdbId'
      path: '/person/$job/$tmdbId'
      fullPath: '/person/$job/$tmdbId'
      preLoaderRoute: typeof PersonJobTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FilmsRouteChildren {
  FilmsTmdbIdRoute: typeof FilmsTmdbIdRoute
}

const FilmsRouteChildren: FilmsRouteChildren = {
  FilmsTmdbIdRoute: FilmsTmdbIdRoute,
}

const FilmsRouteWithChildren = FilmsRoute._addFileChildren(FilmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DirectorsRoute: DirectorsRoute,
  DocsRoute: DocsRoute,
  FilmsRoute: FilmsRouteWithChildren,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  PersonJobTmdbIdRoute: PersonJobTmdbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
